### ISSUE TITLE
文档的网页打开有点慢想自己构建一个本地文档，但是出错啦

### ISSUE THREAD

**Issue by artillerymans** [compose-museum/jetpack-compose-book#313]
clone下来后， 进入项目根目录 npm install，然后就出现这下面的这个错误了，不是很懂npm相关的依赖，寻求帮助
![image](https://user-images.githubusercontent.com/16060581/168259212-749f7147-5f8a-43b7-b844-1aaf4c818deb.png)

**Comment by Nthily** [comment]
检查一下 npm、nodejs 的版本是不是符合 README 上面的要求

**Comment by weizhizhu** [comment]
好咧

**Comment by weizhizhu** [comment]
![image](https://user-images.githubusercontent.com/16060581/168408460-fc9c8daa-17f7-4853-ac0a-dd8c489541e0.png)
这个是我的版本

**Comment by Nthily** [comment]
我自己试了一下没问题，我感觉可能是网络环境问题？我对 npm 也不太熟悉的

**Comment by dingxiansen1** [comment]
我也报了这个错误，npm和nodeJS都是最新的

**Comment by dingxiansen1** [comment]
![image](https://user-images.githubusercontent.com/50258853/169942093-8ba4f974-4942-4d94-a4aa-b3d25f5e04ed.png)

**Comment by LxzBUG** [comment]
解决了吗
我
npm 8.15.0
node v16.17.0 
报错 编译不了

**Comment by Nthily** [comment]
可能是 https://github.com/yanyiwu/nodejieba/issues/208 的原因

**Comment by Nthily** [comment]
我的 node 是 16.15.1，可以正常 install
![image](https://user-images.githubusercontent.com/31311826/191519520-8fa428af-ec30-42f2-a41d-d236d67f8551.png)

**Comment by RugerMcCarthy** [comment]
注意npm版本


------------------ 原始邮件 ------------------
发件人: 超级毛毛虫 ***@***.***&gt;
发送时间: 2022年5月13日 17:53
收件人: compose-museum/jetpack-compose-book ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [compose-museum/jetpack-compose-book] 文档的网页打开有点慢想自己构建一个本地文档，但是出错啦 (Issue #313)





 
clone下来后， 进入项目根目录 npm install，然后就出现这下面的这个错误了，不是很懂npm相关的依赖，寻求帮助

**Comment by artillerymans** [comment]
npm 版本多少

**Comment by whitescent** [comment]
#371
