### ISSUE TITLE
Compose 注解一文中内容表述的疑惑点

### ISSUE THREAD

**Issue by korilin** [compose-museum/jetpack-compose-book#321]
相关文章：https://jetpackcompose.cn/docs/principle/composeAnnotation/

疑惑点：
- 我在 Compose 中并没有找到 `@Compose` 注解，文章中相关的表达是否是想说 `@Composable` 注解呢？
- 标题 **添加$Composer**，如果我没记错这个 $Composer 是一个参数，单词应该是小写的（虽然不影响理解）

```Kotlin
@Composable
public static final void Foo(@Nullable Composer $composer, int $changed)
```

**Comment by Nthily** [comment]
#322 已更正
