### ISSUE TITLE
Text in Basic Components

### ISSUE THREAD

**Issue by Simplation** [compose-museum/jetpack-compose-book#342]
[Text](https://compose-museum.gitee.io/hello-compose/elements/text/#10-%E6%96%87%E5%AD%97%E5%BC%BA%E8%B0%83%E6%95%88%E6%9E%9C)

Replace ~~Icon("这里是禁用后的效果")~~ in the following code with Text("这里是禁用后的效果")

```
// 将内部 Text 组件的 alpha 强调程度设置为禁用
CompositionLocalProvider(LocalContentAlpha provides ContentAlpha.disabled) {
    // where Icon should be replaced with Text
    // Icon("这里是禁用后的效果")
    Text("这里是禁用后的效果") 
}
```

**Comment by Nthily** [comment]
已解决，感谢指出，一直忘记了 😭
