### ISSUE TITLE
Any plan for `androidx.wear.compose.material`

### ISSUE THREAD

**Issue by Flyfish233** [compose-museum/jetpack-compose-book#383]
此项目是否允许，或有计划接收于 [androidx.wear.compose.material](https://developer.android.com/reference/kotlin/androidx/wear/compose/material/package-summary) 的 API 参考文档 ?

**Comment by whitescent** [comment]
可以的，其实我一开始就是想把一些常用的基本组件写进去，带上截图，因为官网这里面的参考文档很少有带运行的截图，有的时候只看代码不太清楚运行后的 UI 是怎么样的。

但是我最近很少有时间维护这个文档了，本来要补充很多内容的，包括 MD3 之类的，文档有很多地方都过时了
