### ISSUE TITLE
关于 '初识 Jetpack Compose 一章节把 Side-effect 翻译成负面影响是否不太恰当？

### ISSUE THREAD

**Issue by iceBear67** [compose-museum/jetpack-compose-book#385]
https://github.com/compose-museum/jetpack-compose-book/blob/91b6ac994b99e98e87c61d12eca4d26af352a66f/docs/tutorial.mdx#L530

我觉得 Compose 里头这个 Side-effect 就是 "UI渲染完成后的副作用"

> Key Term: An effect is a composable function that doesn't emit UI and causes side effects to run when a composition completes.

与其说负面影响 说成副作用是不是更好（

**Comment by whitescent** [comment]
确实，应该写成副作用的，当时可能没仔细留意。
好的！等你的 PR，非常感谢 ❤

**Comment by iceBear67** [comment]
那我丢个pr（
